image: yupix/intsl

stages:
  - local_check
  - package_check
  # - server_create

local_check:
    tags:
        - linux
        - archlinux
        - docker
    stage: local_check
    script:
        - export PATH="$(pwd)/usr/bin:$PATH"
        - intsl -V

package_check:
    tags:
        - linux
        - archlinux
        - docker
    stage: package_check
    script:
        - intsl -V

package_check:server_create:
    tags:
        - linux
        - archlinux
        - docker
    stage: package_check
    script:
        - intsl mc make --type 1 --mcversion 1.8 --server-name aa -y --force --defalut

#server_create_test:
#    tags:
#        - linux
#        - archlinux
#    stage: server_create_test
#    script:
#        - export PATH="$(pwd)/usr/bin:$PATH"
#        - intsl mc make 1 1.15 test -y f
