stages:
  - run_check
  - server_create_test

test:
    tags:
        - linux
        - archlinux
    stage: run_check
    script:
        - export PATH="$(pwd)/usr/bin:$PATH"
        - intsl

server_create_test:
    stage: server_create_test
    script:
        - export PATH="$(pwd)/usr/bin:$PATH"
        - intsl mc make 1 1.8.8 test
